knpu_oauth2_client:
    clients:
        # will create service: "knpu.oauth2.client.passport_oauth"
        # an instance of: KnpU\OAuth2ClientBundle\Client\OAuth2Client

        # configure your clients as described here: https://github.com/knpuniversity/oauth2-client-bundle#configuration
        plage_oauth:
            # this will be one of the supported types
            type: generic
            provider_class: App\Security\PlageProvider

            # optional: a class that extends OAuth2Client
            # client_class: Some\Custom\Client

            # optional: if your provider has custom constructor options
            # provider_options: {}

            # now, all the normal options!

            client_id: '%env(OIDC_CLIENT_ID)%'
            client_secret: '%env(OIDC_CLIENT_SECRET)%'
            # the route that you're redirected to after
            # see the controller example below
            redirect_route: oauth_token
            redirect_params: {}
            # whether to check OAuth2 "state": defaults to true
            use_state: true