version: '3.8'
services:
  # PHP Service
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: ${APP_SLUG}_php
    restart: unless-stopped
    environment:
      SERVICE_NAME: ${APP_SLUG}_php
      SERVICE_TAGS: ${APP_ENV}
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/conf.d/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    networks:
      - app_network

  # Nginx Service
  nginx:
    image: nginx:1.25
    container_name: ${APP_SLUG}_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app_network

  # Mysql Service
  database:
    image: mysql:8.0
    container_name: ${APP_SLUG}_database
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      SERVICE_TAGS: ${APP_ENV}
      SERVICE_NAME: ${APP_SLUG}_database
    volumes:
      - ./storage-db:/var/lib/mysql/
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app_network

  # Mailcatcher Service
  mailcatcher:
    image: schickling/mailcatcher
    container_name: mailcatcher
    restart: unless-stopped
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - app_network

  # Minio Service
  minio:
    image: 'minio/minio:latest'
    ports:
      - '${FORWARD_MINIO_PORT:-9000}:9000'
      - '${FORWARD_MINIO_CONSOLE_PORT:-9090}:9090'
    environment:
      MINIO_ROOT_USER: 'minio'
      MINIO_ROOT_PASSWORD: 'minio123'
    volumes:
      - './docker/aws/minio:/data/minio'
    command: minio server /data/minio --console-address ":9090"
    networks:
      - app_network

# Docker Networks
networks:
  app_network:
    driver: bridge